parsers:
  - name: CXXParser
    package: '@agoraio-extensions/cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/${SDK_VERSION}/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/${SDK_VERSION}/include/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/${SDK_VERSION}/include/time_utils.h'
          - '@agoraio-extensions/terra_shared_configs:headers/${SDK_VERSION}/include/IAgoraMediaComponentFactory.h'

  - name: AddNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      customHeaderFileNamePrefix: 'Custom'
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/${SDK_VERSION}/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/${SDK_VERSION}/include/*.h'
          - '@agoraio-extensions/terra_shared_configs:headers/${SDK_VERSION}/custom_headers/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/${SDK_VERSION}/include/time_utils.h'
          - '@agoraio-extensions/terra_shared_configs:headers/${SDK_VERSION}/include/IAgoraMediaComponentFactory.h'

  - name: RemoveNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: PointerToArrayParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: IrisApiIdParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: UpdateSimpleTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: ReturnTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: FixEnumConstantParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: MergeNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: OrderNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
