name: Fetch AI JSON

on:
  repository_dispatch:
    types: [fetch_ai_json]
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the native headers'
        type: 'string'
        required: true
      product_type:
        description: 'product type, available options: rtc, rtm'
        type: 'string'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/fetch_ai_json
        with:
          url: ${{ inputs.url }}
          product_type: ${{ inputs.product_type }}
