name: Update native headers

on:
  repository_dispatch:
    types: [update_headers]
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the native headers'
        type: 'string'
        required: true
      ai_json_url:
        description: 'URL of the AI JSON'
        type: 'string'
        required: false
      version:
        description: 'native headers version'
        type: 'string'
        required: true
      product_type:
        description: 'product type'
        type: 'string'
        required: true

jobs:
  update-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/update_headers
        with:
          url: ${{ inputs.url }}
          version: ${{ inputs.version }}
          product_type: ${{ inputs.product_type }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ai_json_url: ${{ inputs.ai_json_url }}
          target_repository: ${{ github.repository }}
          target_branch: ${{ github.ref_name }}
