name: Update native headers

on:
  repository_dispatch:
    types: [update_headers]
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the native headers'
        type: 'string'
        required: true
      version:
        description: 'native headers version'
        type: 'string'
        required: false
      custom_headers_version:
        description: 'custom headers version'
        type: 'string'
        required: false

jobs:
  update-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Update headers
        run: |
          bash scripts/update_headers.sh ${{ inputs.url }} ${{ inputs.version }} ${{ inputs.custom_headers_version }}
        shell: bash

      - name: Create pull request
        uses: AgoraIO-Extensions/actions/.github/actions/pr@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          target-repo: ${{ github.workspace }}
          target-branch: ${{ github.ref_name }}
          target-branch-name-surffix: headers-update
          pull-request-title: |
            [AUTO] Update native headers
          pull-request-body: |
            native headers source:
            ${{ inputs.url }}
          add-paths: headers/*
