name: Update native headers

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the native headers'
        type: 'string'
        required: true

jobs:
  update-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Update headers
        run: |
          sh scripts/update_headers.sh ${{ inputs.url }}
        shell: bash

      - name: Create pull request
        uses: AgoraIO-Extensions/actions/.github/actions/pr@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          target-repo: ${{ github.workspace }}
          target-branch: ${{ github.ref_name }}
          target-branch-name-surffix: headers-update
          pull-request-title: |
            [AUTO] Update native headers
          pull-request-body: |
            sdk:
            ${{ inputs.type }}_${{ inputs.version }}
            native source:
            ${{ inputs.url }}
          add-paths: headers/*
