name: Update native headers

on:
  repository_dispatch:
    types: [update_headers]
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the native headers'
        type: 'string'
        required: true
      ai_json_url:
        description: 'URL of the AI JSON'
        type: 'string'
        required: false
      version:
        description: 'native headers version'
        type: 'string'
        required: true
      product_type:
        description: 'product type'
        type: 'string'
        required: true

jobs:
  update-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Update headers
        run: |
          bash scripts/update_headers.sh ${{ inputs.url }} ${{ inputs.version }} ${{ inputs.product_type }}
        shell: bash

      - name: Fetch AI JSON if ai_json_url is provided
        if: ${{ inputs.ai_json_url != '' }}
        uses: ./.github/actions/fetch_ai_json
        with:
          url: ${{ inputs.ai_json_url }}
          product_type: ${{ inputs.product_type }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: AgoraIO-Extensions/actions/.github/actions/pr@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          target-repo: ${{ github.workspace }}
          target-branch: ${{ github.ref_name }}
          target-branch-name-surffix: headers-update
          pull-request-title: |
            [AUTO] Update native headers to ${{ inputs.product_type }}_${{ inputs.version }}
          pull-request-body: |
            native headers source:
            ${{ inputs.url }}
          add-paths: headers/*
